### PR TITLE
Update gallery-card.js

### PR DESCRIPTION
**Pull request by dnshwork**
please add to the interface the ability to open images in a new window to enlarge them when viewing from a phone. Sometimes you need to look at the details, but the photos that open on your phone cannot be enlarged. To do this you need to add one line of code : < a href= "${this._currentResource().url}" target="_blank">Zoom</a>

### CODE REVIEW

**Comment by TarheelGrad1998** [comment]
Did you test this change with video?  I'm guessing the link will initiate a download, which isn't a huge deal if so.  If you haven't been able to test that, no problem, I will test it and merge when I can.

**Comment by N3rdix** [comment]
Sorry to say but this option is pure nonsense and disturbs all users which do not need this link. When using that in the HA app it opens the browser and you have to switch between apps...

On a modern phone the videos can be played already in fullscreen:
image

If you really need this href then at least give the option to enable/disable it...

**Comment by TarheelGrad1998** [comment]
An option to enable makes sense.  @dnshwork - if you have time to put that in (similar to other show_* options) I'll push it.

**Comment by TarheelGrad1998** [comment]
I added show_zoom option to fulfill this.

**Pull request merged**
